# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b44c83af8d0b853752d0d7394bd8959f7b5c80b7c8e49f0a70ae08b097b150b29d14b7bae01bd2c0d5248cb4f54503e803bf658f21f6cb2f96423225a03a36d

test:
  secret_key_base: 34064b0a93af0b6cad570cfc049aea71ea8157b5842d8bafcc710977b4d42ad21580d9902863df426b4abddb24995bb6d255a2a28ab88c7bf2f6dbea16d740aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
